/*!
@file	  resource.h
@author	  Microsoft Visual C++
@date     27/11/2022
@brief    Auto generated by Microsoft when adding resource to project

@license  Copyright © 2022 DigiPen, All rights reserved.
________________________________________________________________________________________________________*/

//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ASCII-mancer.rc
//
#define IDI_ICON1                       101

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
